### ISSUE TITLE
接口 "查询订单剩余待分金额API" 缺失 IDE 提示

### ISSUE THREAD

**Issue by BraisedFish** [TheNorthMemory/wechatpay-openapi#1]

**Comment by TheNorthMemory** [comment]
https://github.com/TheNorthMemory/wechatpay-openapi/blob/d1bb855c160fb35754a88516edad062593e698bb/src/V3/Profitsharing/Transactions/_transaction_id_/Amounts.php#L12-L19

对应PHP调用代码

```php
$instance->v3->profitsharing->transactions->_transaction_id_->amounts->get(['transaction_id' => 'xxx']);
```

**Comment by BraisedFish** [comment]
> https://github.com/TheNorthMemory/wechatpay-openapi/blob/d1bb855c160fb35754a88516edad062593e698bb/src/V3/Profitsharing/Transactions/_transaction_id_/Amounts.php#L12-L19
> 
> 对应PHP调用代码
> 
> ```
> $instance->v3->profitsharing->transactions->_transaction_id_->amounts->get(['transaction_id' => 'xxx']);
> ```

服务商文档中的接口仍然缺少 IDE 提示
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_4_9.shtml

**Comment by TheNorthMemory** [comment]
感谢反馈，已于 https://github.com/TheNorthMemory/wechatpay-openapi/commit/76c6eaee86bfa8a4202569c84b3055e37fe0ca40 新增, v0.15.18 。

```php
$instance->v3
  ->ecommerce->profitsharing
  ->orders->_transaction_id_
  ->amounts->get(['transaction_id' => 'xxx']);
```
